
  particle.ENGINE.MODULES.ACCESS_MODULE( 'STARTER').NEW_OBJECT('myObjectEmiter',10 , 43.2803125,10,10); 
   particle.ENGINE.MODULES.ACCESS_MODULE( 'STARTER').GAME_OBJECTS.ACCESS('myObjectEmiter').CREATE_ANIMATION( SURF , 'LOOP' , 1 , RESOURCE.money_penny , 629819611423702500 , 'no' , 1,11,1,1,1); 
  particle.ENGINE.MODULES.ACCESS_MODULE( 'STARTER').GAME_OBJECTS.ACCESS('myObjectEmiter').CREATE_PARTICLE('FONTAN'); 